development:
  adapter: sqlite3
  database: db/spender-dev.sqlite3
  pool: 5
  timeout: 5000

test:
  adapter: sqlite3
  database: db/spender-test.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: sqlite3
  database: db/spender.sqlite3
  pool: 5
  timeout: 5000